package use_case.commit;

/**
 * This outlines the format of a request model object to create a commit within CommitInteractor. Commits need
 * these three values, as commitId and timestamp are generated by the system.
 */
public class CommitRequestModel {

    private final String roomId;
    private final String userId;
    private final String message;

    public CommitRequestModel(String roomId, String userId, String message) {
        this.roomId = roomId;
        this.userId = userId;
        this.message = message;
    }

    public String getRoomId() {
        return roomId;
    }

    public String getUserId() {
        return userId;
    }

    public String getMessage() {
        return message;
    }
}
